export default ColourConstants = {
  BACKGROUND_COLOUR: "#EFE2DB",
  TEXT_COLOUR_LIGHT: "#fff",
  TEXT_COLOUR_DARK: "#000",
  PRIMARY_COLOUR: "#8E3200",
  SECONDARY_COLOUR: "#fff",
  PARKING_SLOT_BOOKED: "#DF7857",
  PARKING_SLOT_FREE: "#CBE4DE",
};
