export default StringConstants = {
  SIGNUP_TEXT: "Welcome to Car Parking App! Signup Now!",
  FIRST_NAME_PLACEHOLDER: "Enter First Name",
  LAST_NAME_PLACEHOLDER: "Enter Last Name",
  EMAIL_PLACEHOLDER: "Enter Email",
  PASSWORD_PLACEHOLDER: "Enter Password",
  MOBILE_PLACEHOLDER: "Enter Mobile",
  CONFIRM_PASSWORD_PLACEHOLDER: "Confirm Password",
  SIGNUP_BUTTON: "Sign up",
  JOIN_NOW_BUTTON: "New User?, Join Now",
  LOGIN_TEXT: "Welcome to Car Parking App! Login now!",
  DONT_HAVE_ACCOUNT: "Don't have an account? Signup Now!",
  LOGIN_BUTTON: "Login",
  ALREADY_HAVE_ACCOUNT: "Already have an account? Login Now",
  FORGOT_PASSWORD: "Forgot password?",
  BOOK_SLOT: "Book your slot now!",
  PICK_START_DATE: "PICK DATE FROM",
  PICK_END_DATE: "PICK UPTO DATE",
  APP_NAME: "Library Management App",
};
