# Generated by Django 4.1.7 on 2023-04-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_book_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='booked_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
